### ISSUE TITLE
Any way to make tab bar scrollable ?

### ISSUE THREAD

**Issue by mohity777** [PedroBern/react-native-collapsible-segmented-view#10]

**Comment by PedroBern** [comment]
yes, by writing a custom tab bar, and providing it to the parent component.

**Comment by mohity777** [comment]
I can not find any prop for providing custom Tab bar. How to pass it to parent component? By parent component you mean Segmented.View. Right?

**Comment by PedroBern** [comment]
Yes https://github.com/PedroBern/react-native-collapsible-segmented-view/blob/main/src/SegmentedView.tsx#L65

**Comment by mohity777** [comment]
Oh my bad. It was there in readme. Thanks for the help.
